DROP DATABASE IF EXISTS dyerdb;
DROP USER IF EXISTS `dyeradmin`@`%`;
DROP USER IF EXISTS `dyeruser`@`%`;
CREATE DATABASE IF NOT EXISTS dyerdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `dyeradmin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `dyerdb`.* TO `dyeradmin`@`%`;
CREATE USER IF NOT EXISTS `dyeruser`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `dyerdb`.* TO `dyeruser`@`%`;
FLUSH PRIVILEGES;